
# =========================
# DATABASE
# =========================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/healthcare_db20?createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Samira12}
>>>>>>> Stashed changes

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

# =========================
# FLYWAY
# =========================
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration

# =========================
# REDIS (IMPORTANT FIX)
# =========================
spring.data.redis.host=${SPRING_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_REDIS_PORT:6379}
spring.cache.type=redis

# =========================
# JWT
# =========================
app.secret-key=${APP_SECRET_KEY:e09230a7378d879d4bd8c05a6fc117be00041e30e4833e899be9452e6f31652e}
app.expiration-time=3600000


