services:

  db:
    image: mysql:8.0
    container_name: healthcare-db

    environment:
      MYSQL_DATABASE: healthCare_db
      MYSQL_ROOT_PASSWORD: Samira12

    networks:
      - health-net

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost",
             "-u", "root", "-pSamira12"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s


  redis:
    image: redis:7-alpine
    container_name: healthcare-redis

    ports:
      - "6379:6379"

    networks:
      - health-net

    volumes:
      - redis_data:/data


  app:
    build: .
    container_name: healthcare-app

    ports:
      - "8080:8080"

    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/healthCare_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Samira12

      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379

    networks:
      - health-net


networks:
  health-net:
    driver: bridge


volumes:
  mysql_data:
  redis_data: