services:

  db:
    image: mysql:8.0
    container_name: healthcare-db

    environment:
      MYSQL_DATABASE: healthCare_db
      MYSQL_ROOT_PASSWORD: Samira12

    networks:
      - health-net

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
        test: [ "CMD", "mysqladmin", "ping", "-h", "localhost",
                "-u", "root", "-pSamira12" ]
        interval: 10s
        timeout: 5s
        retries: 10
        start_period: 30s

  app:
    build: .
    container_name: healthcare-app

    ports:
      - "8080:8080"

    depends_on:
      db:
        condition: service_healthy

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/healthCare_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Samira12

    networks:
      - health-net

networks:
  health-net:
    driver: bridge

volumes:
  mysql_data: